# Generated by Django 5.1.3 on 2025-03-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelocompleto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen_src', models.CharField(max_length=255)),
                ('experiencia_requerida', models.IntegerField()),
                ('nivel_requerido', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='reto',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'admin'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10),
        ),
        migrations.CreateModel(
            name='LogroObtenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_obtenidos', to='modelocompleto.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_obtenidos', to='modelocompleto.usuario')),
            ],
        ),
    ]
